### ISSUE TITLE
Which adapter?

### ISSUE THREAD

**Issue by jeremypng** [IOT-DSA/dslink-java-advantech#1]
Wondering what hardware your DSLink for Advantech supports? I was hoping to us it with their OBD-II to RS232 streamer.

**Comment by d-shapiro** [comment]
The DSLink doesn't support any specific hardware per se, it just connects with the Advantech WebAccess API. So in that sense, it supports anything that runs a WebAccess server.

**Comment by jeremypng** [comment]
Gotcha. Thanks.
